version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/friend_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: friend_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql




#  - 💡 При таком запуске создаются два независимых контейнера:
#- app — ваше Spring Boot-приложение (Java),
#- db — PostgreSQL.
#- Они автоматически объединяются в одну виртуальную сеть  Network contactlist-thymeleaf_default  и общаются по именам сервисов (jdbc:postgresql://db:5432/...).
# docker-compose up


